### ISSUE TITLE
Subsequent button presses ignored

### ISSUE THREAD

**Issue by ZoneMR** [mdaskalov/homebridge-tasmota-zbbridge#35]
When using a ProgrammableSwitchEvent Sensor, the first button press triggers the event, but subsequent ones do not.

**To Reproduce:**
Add a ProgrammableSwitchEvent sensor, trigger the event, then try to trigger it again.

**Plugin Config:**

```json
{
    "name": "ZbBridge",
    "mqttTopic": "zbbridge",
    "zbBridgeDevices": [
        {
            "addr": "0x7EC5",
            "type": "sensor",
            "name": "Moes Scene Switch",
            "sensorService": "StatelessProgrammableSwitch",
            "sensorCharacteristic": "ProgrammableSwitchEvent",
            "sensorValuePath": "LidlPower"
        },
    ],
    "mqttBroker": "localhost",
    "platform": "TasmotaZbBridge"
}
```

Bug specifics;
In zbBridgeSensor.js, onStatusUpdate, there is a check for "value !== this.value". This makes sense for sensor updates that aren't events, but prevents events being send where the event type is the same as the last.

**Comment by mdaskalov** [comment]
I will have a look at it. This was meant to reduce load as some values are sent many times. Maybe after delay of 2s the value should be updated. There is no way to detect events.

**Comment by mdaskalov** [comment]
I’ve removed the check in release v1.9.0 

It was necessary to completely rework the SENSOR updates logic as all update events were double because of support for `ZbDeviceTopic` setting.
 
Now the MQTT message handler can distinguish between `.../+/SENSOR` and `.../SENSOR` and only one of the handlers is processing the message.

please give feedback (and a star)!
